### PR TITLE
Solves issue WARNING Glyph not available in font "Courier" during exp…

### PR DESCRIPTION
**Pull request by lmizinski**
…ort for PDF

( https://github.com/quelea-projection/Quelea/issues/164 )

To replicate issue:
1. Create new song
a) title and description can be anything
b) Add żźćłóęśąńłó as song lyrics (Polish characters)
c) add this song to current service
2. Click Schedule >> Export songs to PDF

This can be probably fixed other way (keeping Courier font and including it to the project), but this solution worked for me.

### CODE REVIEW

**Comment by ArvidNy** [comment]
Thank you for tracking down the bug and creating a PR! I only have to minor points before I'd be willing to merge it. 

1) At the moment you've replaced one of the [built-in fonts of the PDF library we use](https://xmlgraphics.apache.org/fop/trunk/fonts.html#Base-14-Fonts), with a font that might not be installed on all systems. I'd much rather see you make it fall back on the other font in case the characters aren't found in the default font: `font-family="Courier, NotoSans"`
2) The font you've selected isn't a monospaced font by default. That means that all characters doesn't have the same width and any chords that you'd export will not be perfectly aligned with the lyrics. Perhaps you could find another monospaced font that have the Polish characters that we could use as fallback?

**Comment by lmizinski** [comment]
Hi,
1. for some reason this is exactly what is causing problem. As you said
Courier is available everywhere, but Quelea is missing some special Polish
characters (which i have on my computer, as well as the guy who put fix
request on github).
 I checked and the fallback version doesn't work. It detects, that Courier
is installed, it goes for it, but then it is missing characters so it
replaces them with # (hash signs).
2. Yeah, i forgot about chords, that would require monospace.
Unfortunatelly no fonts that are already included is monospace. I tried to
copy fonts to bundledfonts folder, but that doesn't seems to work:

[image: image.png]

I tried to make sure that those sizes are included from google fonts, but
unfortunatelly it doesn't work.

Any ideas?
I'll try to make it work tomorrow, but i'm running out of ideas.


Pozdrawiam
Łukasz Miziński

-------------------------------------
mail: ukaszm@gmail.com
tel: +48 798 356 051

**Comment by ArvidNy** [comment]
1) That's strange! I've tested it as well and for me it works as expected when I write `font-family="Courier, NotoSans"`. I suppose you should be able to revert the order and make it use NotoSans in first hand and then fall back on Courier, but then we're still stuck on the monospace issue.
2) Yes, from what I saw on that page I linked to earlier, you should be able to include you're own font. So I suppose that a possible work-around might be to bundle a free monospace font that supports all the needed characters with Quelea and then load that one, but I'm not sure about how to do that I'm afraid. @berry120, I guess you set this up originally, do you have any ideas or helpful experiences with the FOP library?

**Comment by ArvidNy** [comment]
I just did a quick test of adding another font in the `/icons/bundledfonts` directory and it works for me, so perhaps the best approach would be just add a monospace font to that directory? How about Liberation Mono which aims at metric compatibility with Courier New?

**Comment by lmizinski** [comment]
This is exactly what I did:

[image: image.png]

Unfortunately in my case it is still skipping RobotoMono, UbuntuMono.
Even though it is loading them:

[image: image.png]

So I guess the problem is with my setup.
I even attached the fonts so I can use them inside application and it works.
The problem only appears during PDF export:

[image: image.png]


Pozdrawiam
Łukasz Miziński

-------------------------------------
mail: ukaszm@gmail.com
tel: +48 798 356 051

**Comment by ArvidNy** [comment]
That's strange that it doesn't work for you! By the way, the attached images were not added to the GitHub post, so I can't see any of them. Do you mind posting them directly on GitHub instead?

**Comment by lmizinski** [comment]
Sorry, I was replying thorough email.  I edited message so that images are available.

**Comment by ArvidNy** [comment]
Thanks for updating the post! When I tried to add RobotoMono like you suggested, I first got the same results, but if I write `font-family="Courier, Roboto Mono"` (with a space character) I get the desired result. I suppose it's just a matter of finding the right name for the font.

**Comment by lmizinski** [comment]
That did the trick:

image

Thank you for help and whole work with the project!

**Comment by berry120** [comment]
@ArvidNy Sorry for not seeing this earlier! Looks like you're going about it the right way - Fop can be a bit fussy with fonts, but it should be possible to just bundle and reference an alternative one that can deal with these characters. I think everything should be set up to use UTF-8 already, so that should be the only thing needed.

Just remember to update the 2020.0 change log to make a note of the fix :)

**Comment by lmizinski** [comment]
I added note about the fix

**Comment by ArvidNy** [comment]
Great, then I'll merge this! Many thanks for the PR again! 

(Just for future reference, you can link commits to issues by writing e.g. "closes quelea-projection/Quelea#164" and that should make it automatically close when the PR is merged.)

**Pull request merged**
