### PR TITLE
remove redundant imports

### PR DESCRIPTION
**Pull request by prakhar-198**
I have fixed all the files..kindly merge it and if you face any conflicts do let me know.

### CODE REVIEW

**Comment by berry120** [comment]
@prakhar-198 The files are the ones at the top of this issue: https://github.com/quelea-projection/Quelea/issues/393

For example, in LibrarySongList the `import org.apache.poi.ss.formula.functions.T;` line isn't needed. In LivePreviewPanel there's a few more imports that aren't needed:

```
import javafx.event.EventHandler;
import javafx.scene.input.DragEvent;
import javafx.scene.input.KeyEvent;
import javafx.scene.input.MouseEvent;
```

...and so on. No need to do all the files in one go if you'd sooner just pick a few - just note which ones you're doing in the issue.

**Comment by prakhar-198** [comment]
Sure

**Comment by berry120** [comment]
@prakhar-198 Try reloading the gradle project - the dependency definitely exists.

**Comment by berry120** [comment]
@prakhar-198 You seem to have now deleted the files altogether?

**Pull request merged**
