### PR TITLE
Added basic support for Elevanto

### PR DESCRIPTION
**Pull request by supagu**
Added basic support for Elevanto.

You can login to Elevanto via Quelea, and it lists the services and can pull down the songs into Quelea.

### CODE REVIEW

**Comment by berry120** [comment]
Thanks for this! I notice there's a chunk of commented out code in `ElevantoParser` - if that's needed, can that be reinstated (or removed entirely if it's not needed?)

**Comment by supagu** [comment]
I've left that as something Todo in future. I just copied my planning centre code and commented out the bits that i haven't done yet. I could clean them up if you still want me too.

**Comment by berry120** [comment]
We'd either need it put in place (if that's required for it to function) or cleaned up. You say it's something todo in future - just for my interest, what's the advantage of having it there if it works without that code?

**Comment by berry120** [comment]
As an additional point - we'll also need the labels in gb.lang, otherwise none of them will show up for translation (gb.lang is used as the master for this.) There's also a couple of hard coded strings that need to go in the labels file (eg. "You may close this window and return to Quelea", and "Error logging into Elevanto:" - there may be others, I haven't done a thorough check.)

**Comment by supagu** [comment]
I've now cleaned out the comments.

**Comment by supagu** [comment]
I've fixed the translations to gb file. Made the html message also use the languages files.

**Comment by supagu** [comment]
@berry120 do you want to check this with my latest changes? Ta

**Comment by berry120** [comment]
Thanks for the changes - as per Arvid's comment, can you change the code to use the logger to print exceptions rather than `printStackTrace()`? You've done that in most places, but not in `ElevantoLoginDialog` it seems.

**Comment by supagu** [comment]
I've committed fixes for printStackTrace()

**Comment by berry120** [comment]
Great, thanks!

**Pull request merged**
