### PR TITLE
Custom keyboard shortcuts

### PR DESCRIPTION
**Pull request by ArvidNy**
*N.B. I'm just creating a PR of this for it to be looked at when we find the time and when we want to add new features, it doesn't have to be merged right away.*

I've made a way to set custom keyboard shortcuts as an advanced setting (by adding lines to the `quelea.properties` file).

# Customizable shortcuts

Feature | Key name
--------|----------
Create a new song | new.song.keys 
Focus the search area | search.keys
Focus the schedule area | schedule.keys (NEW)
Focus the bible search area | bible.keys (NEW)
Open the options dialog | options.keys
Open the live text dialog | live.text.keys
Open the notice dialog | notices.keys
Toggle the logo button | logo.keys
Toggle the black button | black.keys
Toggle the clear button | clear.keys
Toggle the hide button | hide.keys
Advance to the next slide (also used for remote controls) | advance.keys
Advance to the previous slide (also used for remote controls) | previous.keys

# Default values
new.song.keys=Ctrl,Alt,N
search.keys=Ctrl,L
options.keys=Shortcut,T
live.text.keys=Shortcut,Shift,L
logo.keys=F5
black.keys=F6
clear.keys=F7
hide.keys=F8
advance.keys=Page Down
previous.keys=Page Up
notices.keys=Ctrl,M
schedule.focus.key=Ctrl,D
bible.focus.keys=Ctrl,B

# Accepted keys
Below is a list of all the keys that are possible to combine. Up to four modifiers can be added with any other key like the examples in the default values above.

## Modifiers
Shift
Ctrl
Alt
Shortcut (= Ctrl on Windows, Mac key on Mac)

## Other keys
Enter
Backspace
Tab
Cancel
Clear
Pause
Caps Lock
Esc
Space
Page Up
Page Down
End
Home
Left
Up
Right
Down
Comma
Minus
Period
Slash
0
1
2
3
4
5
6
7
8
9
Semicolon
Equals
A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z
Open Bracket
Back Slash
Close Bracket
Numpad 0
Numpad 1
Numpad 2
Numpad 3
Numpad 4
Numpad 5
Numpad 6
Numpad 7
Numpad 8
Numpad 9
Multiply
Add
Separator
Subtract
Decimal
Divide
Delete
Num Lock
Scroll Lock
F1
F2
F3
F4
F5
F6
F7
F8
F9
F10
F11
F12
F13
F14
F15
F16
F17
F18
F19
F20
F21
F22
F23
F24
Print Screen
Insert
Help
Meta
Back Quote
Quote
Numpad Up
Numpad Down
Numpad Left
Numpad Right
Dead Grave
Dead Acute
Dead Circumflex
Dead Tilde
Dead Macron
Dead Breve
Dead Abovedot
Dead Diaeresis
Dead Abovering
Dead Doubleacute
Dead Caron
Dead Cedilla
Dead Ogonek
Dead Iota
Dead Voiced Sound
Dead Semivoiced Sound
Ampersand
Asterisk
Double Quote
Less
Greater
Left Brace
Right Brace
At
Colon
Circumflex
Dollar
Euro Sign
Exclamation Mark
Inverted Exclamation Mark
Left Parenthesis
Number Sign
Plus
Right Parenthesis
Underscore

### CODE REVIEW

**Review by berry120 — APPROVED** [review]
LGTM - I'm happy for this to be merged if you want to see it in 2021.0, don't think we need to wait for this as it looks relatively low risk!

Just a couple of points:
 - If you want to merge for the next release, could you add an entry in the 2021.0 changelog?
 - Could you also add an issue for adding this functionality to the options dialog, just so we don't lose track of that as something that'd be good to have in the future?

Thanks as always!

**Comment by berry120** [comment]
@ArvidNy Just checking you're ok if this is merged for 2021.0? If so I'll create those points above and get it in 👍

**Comment by ArvidNy** [comment]
Sure, sounds great if you want to merge it for 2021.0!

**Comment by berry120** [comment]
Thanks, that's merged in - new issue is here to track the options dialog work: https://github.com/quelea-projection/Quelea/issues/345

**Pull request merged**
