### PR TITLE
Replaced manual loops with Collection.removeIf()

### PR DESCRIPTION
**Pull request by subhamgcon**
Fixing Issue #414 . Kindly check my edits in the code and if it is correct, please merge it with your main branch. Thank you for this amazing opportunity and have a nice day.

### CODE REVIEW

**Review by berry120 — CHANGES_REQUESTED** [review]
Thanks, that's great! 

Just one minor change - if you could get rid of the unnecessary type in the lambda, changing `(Node node)` to just `node` that'd be great 👍

**Review by subhamgcon — COMMENTED** [review]
Please check now.

**Review by subhamgcon — COMMENTED** [review]
Did on this one too.

**Comment by subhamgcon** [comment]
@berry120 I think removing the Node failed the build. Should i add it again?

**Review by berry120 — CHANGES_REQUESTED** [review]
Sorry, just looked at this in more depth - it's not the `node` that's causing the build to fail, it's because you're literally using `collection.removeIf()`.

We need to call `removeIf()` on the actual collection we want the element(s) to be removed from, which is `getCanvas().getChildren()` in this case. It'd be easiest if you could grab an IDE like IntelliJ to check out the code and check it compiles ok before raising the PR, as that'll tell you exactly what's wrong :-)

**Review by berry120 — CHANGES_REQUESTED** [review]
Thanks, much better! Just a couple of points - can we remove the brackets around "node", and also there's a space in `LyricDrawer` that needs removing to fix the indentation 👍

**Comment by subhamgcon** [comment]
> Thanks, much better! Just a couple of points - can we remove the brackets around "node", and also there's a space in `LyricDrawer` that needs removing to fix the indentation 👍

Kindly check now.

**Comment by berry120** [comment]
@subhamgcon You seem to have removed all the spaces on that line - it was just the single space that needed removing!

**Comment by subhamgcon** [comment]
> @subhamgcon You seem to have removed all the spaces on that line - it was just the single space that needed removing!

Kindly check now.

**Comment by berry120** [comment]
Sorry, still not quite right. Take a look at the snippet here:
Untitled
That first line in green (line 229) needs to line up (i.e. be at the same indentation level) as the lines below it. You need to add two spaces to the front of it to get it to do that.

**Comment by subhamgcon** [comment]
> Sorry, still not quite right. Take a look at the snippet here: Untitled That first line in green (line 229) needs to line up (i.e. be at the same indentation level) as the lines below it. You need to add two spaces to the front of it to get it to do that.

So sorry. Kindly check now.

**Review by berry120 — APPROVED** [review]
Thanks, good job!

**Comment by subhamgcon** [comment]
> Thanks, good job!

Thank you for the amazing guidance. Looking forward to contribute and fix more issues also make less mistake.

**Comment by berry120** [comment]
@subhamgcon No worries - the whole point of these issues is to get people used to creating their first PR and getting used to the process, which I hope has been useful for you!

**Comment by subhamgcon** [comment]
> @subhamgcon No worries - the whole point of these issues is to get people used to creating their first PR and getting used to the process, which I hope has been useful for you!

I learnt a lot and all thanks to you!

**Pull request merged**
