### PR TITLE
Updated Mac icon

### PR DESCRIPTION
**Pull request by micahlt**
This PR closes https://github.com/quelea-projection/Quelea/issues/361 by adding a new Mac `.icns` file in accordance with Apple's new icon guidelines.

### CODE REVIEW

**Comment by ArvidNy** [comment]
Not sure if this is what it's supposed to look like? I thought the white border would be transparent.

Skärmavbild 2021-08-12 kl  08 57 11

**Comment by micahlt** [comment]
Yikes, definitely not!  I'll take a look at that.  Transparency should have been preserved.

**Comment by berry120** [comment]
Side note to @ArvidNy 's point above, but can we also remove the `.DS_Store` file from the PR? Thanks :)

**Comment by berry120** [comment]
Side note to this - I'm hoping to roll out the final beta (all being well) of 2021.0 at some point in the next few days, and happy to put this in there if we can get the transparency fixed. If not then no worries at all, and we can just wait for the next release 👍

**Comment by micahlt** [comment]
Okay, everything should be fine now - I realized that the method I previously used to generate the ICNS doesn't allow transparency.    Hopefully this isn't too late for 2021.0!

**Comment by berry120** [comment]
@micahlt Thanks very much! Could we just get rid of that `DS_STORE` file? 👍

**Comment by micahlt** [comment]
Definitely!  Sorry about that.  Everything appears to be fine now.

**Comment by berry120** [comment]
No worries - thanks very much!

**Comment by ArvidNy** [comment]
I can verify it's working as expected now. Thanks for the PR!
Skärmavbild 2021-09-08 kl  11 40 12

**Pull request merged**
