### PR TITLE
Add preference option to allow song information to appear on first, last or all slides

### PR DESCRIPTION
**Pull request by bezchmurny**
Feedback most welcome.

I have left the main "show" option in place as it's tied in all over the place; this adds to it rather than replaces it.

### CODE REVIEW

**Comment by bezchmurny** [comment]
Added a fix to LyricDrawer based on feedback from @berry120

**Comment by bezchmurny** [comment]
Cleaned up imports in LyricDrawer whilst correcting an IntelliJ automatic change.

**Comment by DeeTigIT** [comment]
This seems not stable, yet:

- When I set the new option on "First" or "Last" and Go live again with the song: the song text is still on **all slides**.
- Also, the setting of the new option is **not preserved** after closing and restarting Quelea.

**Comment by bezchmurny** [comment]
OK, I'm pretty sure this'll be down to something I've done in the preferences pane.

Are you using English (GB), Polish (PL) or another language out of interest?

**Comment by bezchmurny** [comment]
> OK, I'm pretty sure this'll be down to something I've done in the preferences pane.
> 
> Are you using English (GB), Polish (PL) or another language out of interest?

I've reproduced this in French (FR). I never tested it against a language where I hadn't added in labels (lesson learned). I'll take a look tomorrow and see what I missed.

**Comment by bezchmurny** [comment]
Heh. So the use of the LabelGrabber#getEngKey() method of dealing with preferences relies on the keys being there in the current language file. The H/V position properties suffer this same issue in for example Punjabi (PJ).

I'll sleep on whether I make the method more fancy (riskier but more correct) or just add the placeholders in to all languages...!

**Comment by bezchmurny** [comment]
P.S. @DeeTigIT thanks for catching that before it goes to a release version, much appreciated!!

**Comment by DeeTigIT** [comment]
Van: Stephen Sharpe ***@***.***> 
Verzonden: dinsdag 2 januari 2024 22:57
Aan: quelea-projection/Quelea ***@***.***>
CC: DeeTigIT ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [quelea-projection/Quelea] Add preference option to allow song information to appear on first, last or all slides (PR #634)

 

OK, I'm pretty sure this'll be down to something I've done in the preferences pane.

Are you using English (GB), Polish (PL) or another language out of interest?

**Comment by DeeTigIT** [comment]
You’re welcome!

 

Van: Stephen Sharpe ***@***.***> 
Verzonden: dinsdag 2 januari 2024 23:27
Aan: quelea-projection/Quelea ***@***.***>
CC: DeeTigIT ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [quelea-projection/Quelea] Add preference option to allow song information to appear on first, last or all slides (PR #634)

 

P.S. @DeeTigIT <https://github.com/DeeTigIT>  thanks for catching that before it goes to a release version, much appreciated!!

**Comment by bezchmurny** [comment]
@DeeTigIT I believe this should now be fixed; please check :)

**Comment by DeeTigIT** [comment]
Hello Stephen,

 

I’ll check if a new CI release will published this evening. And then test it.

 

Best regards,

 

Dirk

 

Van: Stephen Sharpe ***@***.***> 
Verzonden: woensdag 3 januari 2024 19:08
Aan: quelea-projection/Quelea ***@***.***>
CC: DeeTigIT ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [quelea-projection/Quelea] Add preference option to allow song information to appear on first, last or all slides (PR #634)

 

@DeeTigIT <https://github.com/DeeTigIT>  I believe this should now be fixed; please check :)

**Comment by DeeTigIT** [comment]
My compliments, the setting works now as expected.
And is also saved between Quelea sessions.
Thanks!

**Pull request merged**
