### PR TITLE
Improvments for the remote control web app

### PR DESCRIPTION
**Pull request by ArvidNy**
I've been thinking that the web app for remote controlling Quelea needs some improvements, especially for mobile devices. A while ago I started looking at making it look and function more like the Android app and it seems to be working now to me.

The buttons are now static to the page and the lyrics is the only thing that scrolls. I've added a navigation drawer that looks more like the mobile app and I've also made a simplified search feature that makes it possible to search for songs and add bible passages at the same time.

### Here are some screenshots of the new layout:
remote1
remote2
remote3

---

### Just for reference, here's what the old layout looks like on the same screen size:
old-remote

### CODE REVIEW

**Comment by berry120** [comment]
@ArvidNy Sorry, seem to have missed this entirely - would you still say it's something we should get in place for 2020.0?

**Comment by ArvidNy** [comment]
No worries! I don't mind if we hold this one off until the next release. Just wanted to put this PR in place when I had finished it, so that it could be merged whenever we want to. It seems to be working to me, and none of the changes should affect anything other than the web remote app, but since we've already added a few new features into 2020.0 we might as well save this for the next release.

**Comment by berry120** [comment]
@ArvidNy No worries - I'll see if I can take a look at this in more depth before building the beta, it'd be good to get it in there if we can.

**Comment by berry120** [comment]
Since 2020.0 is already rather late I'll delay this to the release after if that's ok - but will merge as a priority as soon as 2020.0 is out the door.

**Comment by ArvidNy** [comment]
Sounds good to me!

**Comment by berry120** [comment]
Merged this in now that 2020.0 is released.

**Pull request merged**
