### PR TITLE
Replaced Anonymous to lambda in the following files to solve issue #409

### PR DESCRIPTION
**Pull request by Devansh-gaur-1611**
I have Replaced Anonymous to lambda in the following files
AddImageActionHandler
AddPdfActionHandler
AddPowerpointActionHandler
AddSongPromptOverlay
BasicSongPanel
BigDecimalSpinner
BigDecimalTextField
BooleanCell
ClearingEventHandler
DisplayPositionSelector
DisplayStage
EditSongDBActionHandler
EditThemeDialog
ExitActionHandler

### CODE REVIEW

**Review by berry120 — CHANGES_REQUESTED** [review]
Good effort!

When replacing these classes to make them lambdas though you can do a lot more than just removing the first line and replacing it with `()->` - the entire implementation, including the inner method, can be removed to leave minimal boilerplate, which is what we're after here.

Take a look at this PR which should help indicate what we're after: https://github.com/quelea-projection/Quelea/pull/410/files

**Comment by Devansh-gaur-1611** [comment]
Hi @berry120, I have done all the changes requested by you, please have a look over it .
However, I needs your help .Can you please tell me what is this message means (All checks are failed). I don't know much about much it as I am just a beginner to open source . Is this fine

**Comment by berry120** [comment]
@Devansh-gaur-1611 Afraid not, the project doesn't compile after your changes - you'll need to work out what the compilation errors are and then solve them 👍

**Comment by berry120** [comment]
Note: relates to #409

**Review by berry120 — CHANGES_REQUESTED** [review]
Project will need to compile successfully before we accept this PR.

**Comment by Devansh-gaur-1611** [comment]
@berry120, All checks are passed now with your above advice. Thanks for that. Can u please tell me is any other change required

**Review by berry120 — CHANGES_REQUESTED** [review]
Thanks for this! All the lambdas look good from a quick glance.

Few points:

 - Looks like there's a bunch of formatting changes - can we wind these back? Mostly new lines in comments and between import statements.
 - We're now importing `javax.swing.*` in `BigDecimalSpinner` - can we get rid of this and just import any classes we need individually?

**Comment by Devansh-gaur-1611** [comment]
> * Looks like there's a bunch of formatting changes - can we wind these back? Mostly new lines in comments and between import statements.
Hello @berry120 sir, I have just done formatting changes just to align the text which has taken place due to changing the anonymous to lambda.Also ,If I revert back the changes I have to again start all the things from beginning, so sir can we ignore it plz

> * We're now importing `javax.swing.*` in `BigDecimalSpinner` - can we get rid of this and just import any classes we need individually?
Actually sir ,the main reason behind it was in the line 44(in my commit), there it is written " {@link JSpinner} " so when I remove " javax.swing.* " ,it shows me error

**Comment by berry120** [comment]
@Devansh-gaur-1611 The formatting changes with the lambdas are fine - the changes I'm referring to are mainly those new lines in the Javadoc comments and the import statements. No need to start again, just make a new commit to remove them.

In terms of `javax.swing.*` - absolutely no problem with importing only `JSpinner`, but we certainly don't need to import the entire swing package just for that!

**Comment by Devansh-gaur-1611** [comment]
Hello Mr @berry120 sir, I have undone all the formatting changes in the Javadoc comments. Sir, please have a look over it

**Comment by berry120** [comment]
@Devansh-gaur-1611 Looks good, thanks! Just the import to fix now and then we're good to merge 👍

**Comment by Devansh-gaur-1611** [comment]
> @Devansh-gaur-1611 Looks good, thanks! Just the import to fix now and then we're good to merge 👍

Hello @berry120 sir, I have tried to remove that import but when I have removed that import, It is showing an error and thus have conflicted in one of my previous pull requests, due to this, sir I am unable to remove that import otherwise it will not be able to pass all the checks.
Thus I request you sir that you, on your own try to remove that import. Please sir

**Comment by Devansh-gaur-1611** [comment]
hello @berry120 sir, please tell me what should I do now as I am unable to remove that import (for details ,please refer my previous comment).

**Comment by berry120** [comment]
@Devansh-gaur-1611 You can import the *specific* class you need (`JSpinner`) from `javax.swing` - i.e. doing `javax.swing.JSpinner` instead of `javax.swing.*`. If you're still getting an error when you do that, paste the error here and I'll take a look.

**Comment by Devansh-gaur-1611** [comment]
Hello @berry120 sir, I have changed the imports from javax.swing.* to javax.swing.JSpinner and it is showing no error. Thanks for your help, sir. Also, I am sorry that I haven't understood this same thing that you have told me in your previous comment previously.

**Comment by Devansh-gaur-1611** [comment]
Hello @berry120 sir, I have done the import changes. Sir can you please tell me that is any other changes are required or my pr is now good to merge

**Review by berry120 — APPROVED** [review]
Thanks!

**Comment by Devansh-gaur-1611** [comment]
Hello @berry120 sir, Thanks for accepting my pr and also thanks for helping me and guiding me at every stage during the solving of this issue.

**Pull request merged**
