### PR TITLE
Jessy jp branch for pull req

### PR DESCRIPTION
**Pull request by JessyJP**
This is probably my first ever proper pull request, although I did try before.
Anyway, just a minor bug fix and extra ignore for the IntelliJ Idea IDE.
I hope it gets accepted quick and easy so I can see how it works and send some other pull requests later.

### CODE REVIEW

**Review by berry120 — COMMENTED** [review]
Thanks for the PR! Couple of comments:

 - If we're modifying the remote control server there, then we should really remove the `close()` and `flush()` lines entirely, and use the "try with resources" construct (https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) to auto-close the output stream.
 - Think we should just have `.idea/` in the ignore file and then remove `Quelea/.idea/*` if we're changing that, as that will ignore the `.idea` folder wherever it happens to be (even if someone opens a separate folder as a subproject somehow.)

**Comment by JessyJP** [comment]
- I was testing transposing a song from a MIDI controller in Reaper and it kept throwing errors.
I am thinking WHY? Then I noticed the call sequence and fixed it to the point of not throwing errors. 
It worked but it was still a bit strange as it sometimes transposed and sometimes it didn't.
Maybe that's related to what you mentioned about "try with resources".

- For me with idea 2022 it wanted to add about 8 or 9 files, just added that in the end and that ignored them.
I think it's fine to leave both even if for some it may be redundant. 
I guess I don't know about everyone else but I open the project at the repository dir level and it opens fine. Perhaps other people open from <repo Quelea>/Quelea which is why the first option works for them.

I guess the commits could be accepted for now and then come back to it in the future.
At some point, a transpose up and down should be included in the stage control.

**Comment by berry120** [comment]
Hey, few points here:

 > I was testing transposing a song from a MIDI controller in Reaper and it kept throwing errors.
I am thinking WHY? Then I noticed the call sequence and fixed it to the point of not throwing errors.
It worked but it was still a bit strange as it sometimes transposed and sometimes it didn't.
Maybe that's related to what you mentioned about "try with resources".

No, the try with resources is a stylistic thing in code - it will essentially flush & close the stream after the code contained within that block is complete, rather than having to call `close()` manually. The link I pasted should give you some more context there - it's essentially a neater way of achieving the same thing, and also comes with some additional guarantees (for example, the stream will always be closed even if an exception occurs.)

 > I think it's fine to leave both even if for some it may be redundant.

It's not a case of it being redundant for some - the extra entry would be redundant for everyone, as just specifying `.idea/` in `.gitignore` ignores it in *any* directory, including `Quelea/.idea`. So there's never a need to have both (so long as I'm remembering the `.gitignore` syntax correctly, that is.) If you specified `/.idea/` (note the extra slash at the beginning) then that would be specific to the top level directory and so we'd need both - but don't think that's necessary here. Just need to remove that extra entry.

 > I guess the commits could be accepted for now and then come back to it in the future.

Afraid that's not how the process works :-) This is why we have a review process - to ensure any external code or changes we're accepting is the best possible quality it can be, even if it's just one-liners like the above. In reality "coming back to it in the future" never tends to happen, so the best time to sort these things is now, before we merge.

**Comment by JessyJP** [comment]
"t's not a case of it being redundant for some - the extra entry would be redundant for everyone, as just specifying .idea/ in .gitignore ignores it in any directory, including Quelea/.idea. So there's never a need to have both (so long as I'm remembering the .gitignore syntax correctly, that is.) If you specified /.idea/ (note the extra slash at the beginning) then that would be specific to the top level directory and so we'd need both - but don't think that's necessary here. Just need to remove that extra entry."

**Comment by JessyJP** [comment]
I get what you mean it's the pattern in the file path rather than the path itself. So the Quelea/.idea/* becomes redundant. And

**Comment by berry120** [comment]
> if I am supposed to resubmit an edited version you have to tell me explicitly.

Yes please :-) You can update your current branch and then it'll update the PR here.

To be clear, as to the try with resources point, you can replace this:

```
        OutputStream os = he.getResponseBody();
        os.write(response.getBytes(Charset.forName("UTF-8")));
        os.flush();
        os.close();
```

With just this:

```
        try(OutputStream os = he.getResponseBody()) {
            os.write(response.getBytes(Charset.forName("UTF-8")));
        }
```

...and in the other file, delete the superfluous gitignore entry as described above.

**Comment by JessyJP** [comment]
The changes are done. In the process, there were some syncing peculiarities, which resulted in a bunch of merges. 
I tried to squash the commits so that they appear as only 2 commits but this was the result in the end. I don't know if that's a problem.
There definitely seems to be a delicate order to fetching, squashing, merging, uploading, etc.!

**Comment by berry120** [comment]
No problem with multiple commits - the only thing the reviewers (me in this case) really care about is the diff, which all looks good. Commits all get squashed into one anyway.

**Pull request merged**
