### PR TITLE
Add live item indicator

### PR DESCRIPTION
**Pull request by ksandhu16**

### CODE REVIEW

**Comment by DeeTigIT** [comment]
Hello ksandhu16,
Is it perhaps possible in this stage to fill already the description of this interesting change?
Regards and blessings,
Dirk

**Comment by berry120** [comment]
Apologies for taking a while to reply to this!

As Dirk said, we'd need a description of what's changed here before considering whether to accept it (seems to be an icon of some description added somewhere at a quick glance?)

There's also a bunch of formatting changes (new lines, extra spaces) that are [cluttering up the diff](https://github.com/quelea-projection/Quelea/pull/65/files) - it's important to remove those too so we can more clearly see what's *actually* functionally changed in this PR.

**Comment by ArvidNy** [comment]
Looks like a simple copy-paste of [this branch](https://github.com/quelea-projection/Quelea/tree/live-item-indicator), so perhaps he doesn't even know himself what this does.

As we discussed per email before, this adds an icon to the item that is live instead of having a live color, looking like this:
live-item-icon

Regarding the formatting changes, that looks like the changes that IntelliJ makes when it's formatting the code. I haven't found a setting for it to use the same formatting style as Netbeans to be able to avoid this yet, but I'm sure it's possible.

**Comment by berry120** [comment]
> Regarding the formatting changes, that looks like the changes that IntelliJ makes when it's formatting the code. I haven't found a setting for it to use the same formatting style as Netbeans to be able to avoid this yet, but I'm sure it's possible.

That's fine in the branch where we know who wrote it and what it does, so I wouldn't worry about that too much. I was just more cautious in a random PR with no other details!

I think this would be a good thing to merge in at some point, but clearly this PR isn't the way to do it - I'll close this off and we'll look at merging your *actual* branch in later!

**Pull request closed without merging**
